### ISSUE TITLE
Add the feature of webpage sharing on social platforms 

### ISSUE THREAD

**Issue by kanika321** [atapas/shoes#6]
Using javascript to share the webpage with a single click as a post on fb, twitter, pinterest, linkedin and whatsapp.

**Comment by harshcoder7** [comment]
i can work on this issue asap, plz provide me this opportunity, thanks!

**Comment by kanika321** [comment]
I actually wanted to add that section. The issue was raised for assignment.

**Comment by justkingsley** [comment]
Hello, can you please add the hactoberfest label I wan to contribute.

**Comment by justkingsley** [comment]
hello @atapas I am trying to run the project and keep getting this error when I run gatsby develop. Can you please assist me with that.

![image](https://user-images.githubusercontent.com/26405672/198560943-776fafb2-4fd6-4ec4-abb4-7d2b32d3de42.png)

**Comment by atapas** [comment]
> hello @atapas I am trying to run the project and keep getting this error when I run gatsby develop. Can you please assist me with that.
> 
> ![image](https://user-images.githubusercontent.com/26405672/198560943-776fafb2-4fd6-4ec4-abb4-7d2b32d3de42.png)

I think, you are not running the backend project in the separate terminal. Please read the readme.

**Comment by AlexHRodrii** [comment]
Can I work on that issue?

**Comment by atapas** [comment]
> Can I work on that issue?
> 
> 

Sure

**Comment by AlexHRodrii** [comment]
> > hello @atapas I am trying to run the project and keep getting this error when I run gatsby develop. Can you please assist me with that.
> > ![image](https://user-images.githubusercontent.com/26405672/198560943-776fafb2-4fd6-4ec4-abb4-7d2b32d3de42.png)
> 
> I think, you are not running the backend project in the separate terminal. Please read the readme.

I also had that error, I fixed it adding some products and companies in the strapi admin console. It's caused because graphQL query throws error because there are not elements in the collection.
